name: Postman Tests Script

on:
  push:
    branches: [ "main" ]
env:
  CACHE_VERSION: v1
jobs:
  postman-tests:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
      
    - name: Cache npm
      uses: actions/cache@v4
      with:
        path: ~\AppData\Roaming\npm-cache
        key: ${{ runner.os }}-npm-global-bin-${{ env.CACHE_VERSION }}
        restore-keys: |
          ${{ runner.os }}-npm-global-bin-
    
    - name: Install Newman and HTML Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-html

    - name: Create cert and key files
      shell: bash
      run: |
          echo "$API_CLIENT_CERT" > client-cert.pem
          echo "$API_CLIENT_KEY" > client-key.pem
      env:
          API_CLIENT_CERT: ${{ secrets.API_CLIENT_CERT }}
          API_CLIENT_KEY: ${{ secrets.API_CLIENT_KEY }}
    
    - name: Run Dev Revenir Postman Collection
      shell: bash
      run: |
            newman run "postman/Dev-Revenir Complete Flow.postman_collection.json" \
            --ssl-client-cert client-cert.pem \
            --ssl-client-key client-key.pem \
            --delay-request 1000 \
            --reporters cli,json,html \
            --reporter-json-export "postman/newman-report.json" \
            --reporter-html-export "postman/newman-report.html"
            
    - name: Upload Newman Test Report
      uses: actions/upload-artifact@v4
      with:
        name: newman-report
        path: postman/newman-report.json

    - name: Upload Newman HTML Report
      uses: actions/upload-artifact@v4
      with:
       name: newman-html-report
       path: postman/newman-report.html
