name: Run Postman Tests on Windows

on:
  push:
    branches: [ "main" ]

jobs:
  postman-tests:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Newman and HTML Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-html
    
    - name: Run Dev Revenir Postman Collection (Windows)
      run: |
        newman run "postman/Dev-Revenir Complete Flow.postman_collection.json" `
          --environment "postman/revenir-env.json" `
          --working-dir ./postman/images \
          --reporter-json-export "postman/newman-report.json"
    
    - name: Upload Newman Test Report
      uses: actions/upload-artifact@v4
      with:
        name: newman-report
        path: postman/newman-report.json
